/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TmxButton {
        /**
          * Defining Buttons' label
         */
        "label": string;
        /**
          * Defining a Buttons's variations
         */
        "variation": string;
    }
    interface TmxPresentation {
    }
}
declare global {
    interface HTMLTmxButtonElement extends Components.TmxButton, HTMLStencilElement {
    }
    var HTMLTmxButtonElement: {
        prototype: HTMLTmxButtonElement;
        new (): HTMLTmxButtonElement;
    };
    interface HTMLTmxPresentationElement extends Components.TmxPresentation, HTMLStencilElement {
    }
    var HTMLTmxPresentationElement: {
        prototype: HTMLTmxPresentationElement;
        new (): HTMLTmxPresentationElement;
    };
    interface HTMLElementTagNameMap {
        "tmx-button": HTMLTmxButtonElement;
        "tmx-presentation": HTMLTmxPresentationElement;
    }
}
declare namespace LocalJSX {
    interface TmxButton {
        /**
          * Defining Buttons' label
         */
        "label"?: string;
        /**
          * Defining a Buttons's variations
         */
        "variation"?: string;
    }
    interface TmxPresentation {
    }
    interface IntrinsicElements {
        "tmx-button": TmxButton;
        "tmx-presentation": TmxPresentation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tmx-button": LocalJSX.TmxButton & JSXBase.HTMLAttributes<HTMLTmxButtonElement>;
            "tmx-presentation": LocalJSX.TmxPresentation & JSXBase.HTMLAttributes<HTMLTmxPresentationElement>;
        }
    }
}
